name: test_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.1.2
  cupertino_icons:
  flutter_bloc: ^8.1.3
  built_value: ^8.6.1
  equatable: ^2.0.5
  flutter_svg: ^2.0.6
  dio: ^5.2.1+1
  dio_cache_interceptor: ^3.4.2
  flutter_dash: ^1.0.0
  intl: ^0.18.1
  connectivity_plus: ^4.0.1
  shimmer: ^3.0.0
  bloc_concurrency: ^0.2.2
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.1
  flutter_hooks: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.0
  built_value_generator: ^8.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/static/
    - assets/svg/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light-Italic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
